[theme]
base = "dark"
primaryColor = "#f5c542"  # a warm professional yellow
secondaryBackgroundColor = "#1e1e2f"  # dark muted background
textColor = "#f0f0f0"  # light text for readability
font = "sans serif"  # clean professional font